/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/user/avatar.vue')['default']
    Background: typeof import('./src/components/background.vue')['default']
    'Bilibili.ce': typeof import('./src/components/bilibili.ce.vue')['default']
    Categorie: typeof import('./src/components/sideBar/categorie.vue')['default']
    Categories: typeof import('./src/components/categories/index.vue')['default']
    CheckIn: typeof import('./src/components/sideBar/checkIn.vue')['default']
    Comment: typeof import('./src/components/comment/comment.vue')['default']
    CommentChild: typeof import('./src/components/comment/commentChild.vue')['default']
    CommentVote: typeof import('./src/components/monf/commentVote.vue')['default']
    DownloadApp: typeof import('./src/components/sideBar/downloadApp.vue')['default']
    I18n: typeof import('./src/components/header/i18n.vue')['default']
    Item: typeof import('./src/components/article/item.vue')['default']
    ListStatus: typeof import('./src/components/listStatus.vue')['default']
    MoblieHeader: typeof import('./src/components/header/moblieHeader.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NImage: typeof import('naive-ui')['NImage']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PageFooter: typeof import('./src/components/sideBar/pageFooter.vue')['default']
    PcHeader: typeof import('./src/components/header/pcHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollView: typeof import('./src/components/scrollview/scrollView.vue')['default']
    Search: typeof import('./src/components/header/search.vue')['default']
    ShowComment: typeof import('./src/components/article/showComment.vue')['default']
    SideBar: typeof import('./src/components/sideBar/index.vue')['default']
    Tag: typeof import('./src/components/article/tag.vue')['default']
    UseHeader: typeof import('./src/components/header/useHeader.vue')['default']
    UseIcon: typeof import('./src/components/useIcon.vue')['default']
    UserHeader: typeof import('./src/components/comment/userHeader.vue')['default']
  }
}
